[package]
name = "backgammon"
version = "0.1.2"
edition = "2024"

[dependencies]
rand = "0.9.1"
rayon = "1.10.0"
hashbrown = "0.15.4"
nannou = { version = "0.19.0" }

[profile.release]
strip = true
# lto = true